module = {}

module.TILE_SIZE = 16
module.ROOM_BUFFER = 16
module.CAMERA_SPEED = 300
module.WORLD_WIDTH = 800
module.WORLD_HEIGHT = 2000
module.MONSTER_MOVE_SPEED = 100
module.DEBUG_LINES_ENABLED = true
module.DISPLAY_FPS_ENABLED = true
module.MONSTER_WAIT_SECONDS = 1.0
module.ADVENTURER_SPAWN_DELAY = 2.0
module.ADVENTURER_MOVE_SPEED = 100

return module